"""empty message

Revision ID: 79305234197c
Revises: f8998a665d02
Create Date: 2020-04-01 19:38:37.809832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79305234197c'
down_revision = 'f8998a665d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_profile_biography_key', 'user_profile', type_='unique')
    op.drop_constraint('user_profile_email_key', 'user_profile', type_='unique')
    op.drop_constraint('user_profile_first_name_key', 'user_profile', type_='unique')
    op.drop_constraint('user_profile_gender_key', 'user_profile', type_='unique')
    op.drop_constraint('user_profile_last_name_key', 'user_profile', type_='unique')
    op.drop_constraint('user_profile_location_key', 'user_profile', type_='unique')
    op.drop_constraint('user_profile_photo_key', 'user_profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_profile_photo_key', 'user_profile', ['photo'])
    op.create_unique_constraint('user_profile_location_key', 'user_profile', ['location'])
    op.create_unique_constraint('user_profile_last_name_key', 'user_profile', ['last_name'])
    op.create_unique_constraint('user_profile_gender_key', 'user_profile', ['gender'])
    op.create_unique_constraint('user_profile_first_name_key', 'user_profile', ['first_name'])
    op.create_unique_constraint('user_profile_email_key', 'user_profile', ['email'])
    op.create_unique_constraint('user_profile_biography_key', 'user_profile', ['biography'])
    # ### end Alembic commands ###
