"""empty message

Revision ID: f8998a665d02
Revises: 
Create Date: 2020-03-31 20:40:05.739283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8998a665d02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('gender', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('biography', sa.String(length=450), nullable=True),
    sa.Column('photo', sa.String(length=120), nullable=True),
    sa.Column('user_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('biography'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('first_name'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('location'),
    sa.UniqueConstraint('photo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###
